      SUBROUTINE CLOCKV ( VECTIM , NEWTIM , IDUM1 , IDUM2 )
      DOUBLE PRECISION VECTIM,NEWTIM
      REAL XI1,XARRAY(2)
      EXTERNAL ETIME
      CALL cpu_time (XI1)
      NEWTIM=1.0D+03*XI1
      VECTIM=0.0D+00
      RETURN
      END
