      SUBROUTINE MUEDK0(VALSYM,INTSYM,
     1                  VALASY,INTASY,
     2                  SMAT,
     2                  NOBAL,NOBAR,NOPERS,
     2                  ISTOFF,JSTOFF,
     2                  HMAT,IDIMRO,IDIMCO,
     2                  NDIMRO,NDIMCO, 
     2                  V2MP1R,V2MP1C,
     2                  JMAXP1,KKP1,
     2                  NDIPSY,NDIPAS,
     2                  SYMM,
     2                  AABB,
     2                  NABSR,NABSC,
     1                  PSEUR,PSEUC)
C
      IMPLICIT REAL*8 (A-H,O-Z)
      INTEGER V2VAL(10),NSVAL(10)
C
      COMMON /AMPDI/ IDPMA,IDPTR
C
      INTEGER PRTINT
C
      LOGICAL SYMM,AABB
      INTEGER NABSR,NABSC 
      CHARACTER*2 SLABR,SLABC
      CHARACTER*1 PSEUR,PSEUC
      REAL*8 VALSYM(INTSYM)
      REAL*8 VALASY(INTASY)
      REAL*8 SMAT(NOBAL,NOBAR,NOPERS)
      REAL*8 HMAT(IDIMRO,IDIMCO)
      INTEGER V2MP1R,V2MP1C 
C
      include 'rensys.h'
C
      KBDSYM=0
      KBDASY=0
C
      DO 99 JL=1,IDIMCO
      DO 99 IR=1,IDIMRO
99    HMAT(IR,JL)=0.0D+00
C
      DO 940 KP1=1,JMAXP1
C
      DO 920 INDEX1=1,V2MP1R
      DO 900 INDEX2=1,V2MP1C
C
      KBDSYM=KBDSYM+1
      IOFFSY=(KBDSYM-1)*NDIPSY
      IF (.NOT.SYMM) THEN
          KBDASY=KBDASY+1
          IOFFAS=(KBDASY-1)*NDIPAS
      ENDIF
C
      IF (KP1.NE.KKP1) GOTO 900
C
      KNDEX=0
C
      IROWOF=(INDEX1-1)*NDIMRO
      ICOLOF=(INDEX2-1)*NDIMCO
C
C  1. LEADING TERM (NOT DEPENDING ON STRETCHING COORDINATES)
C
      IF (AABB) THEN
      IF (.NOT. SYMM) THEN
      G = VALSYM(IOFFSY+1)
      DO 100 IR=1,NDIMRO
100   HMAT(IROWOF+IR,ICOLOF+IR)=HMAT(IROWOF+IR,ICOLOF+IR)
     1                       +G
      ENDIF
      ELSE
      KNDEX=KNDEX+1
      IF (.NOT. SYMM) THEN
      G = VALSYM(IOFFSY+1)
      DO 101 IR=1,NDIMRO
      DO 101 JL=1,NDIMCO
101   HMAT(IROWOF+IR,ICOLOF+JL)=HMAT(IROWOF+IR,ICOLOF+JL)
     1                       +G*SMAT(ISTOFF+IR,JSTOFF+JL,KNDEX)
      ENDIF
      ENDIF
C
C  2. TERMS CONTAINING Y1
C
      KNDEX=KNDEX+1
      G = VALSYM(IOFFSY+2)
      DO 120 JL=1,NDIMCO
      DO 120 IR=1,NDIMRO
120   HMAT(IROWOF+IR,ICOLOF+JL)=HMAT(IROWOF+IR,ICOLOF+JL)
     1                 +G*SMAT(ISTOFF+IR,JSTOFF+JL,KNDEX)
C
C 3. TERMS CONTAINING Y3
C
      KNDEX=KNDEX+1
      G=-G
      IF (.NOT. SYMM) G = VALASY(IOFFAS+1)
      DO 140 JL=1,NDIMCO
      DO 140 IR=1,NDIMRO
140   HMAT(IROWOF+IR,ICOLOF+JL)=HMAT(IROWOF+IR,ICOLOF+JL)
     1                 +G*SMAT(ISTOFF+IR,JSTOFF+JL,KNDEX)
C
C  4. TERMS CONTAINING Y1*Y1
      KNDEX=KNDEX+1
      G = VALSYM(IOFFSY+3)
      DO 160 JL=1,NDIMCO
      DO 160 IR=1,NDIMRO
160   HMAT(IROWOF+IR,ICOLOF+JL)=HMAT(IROWOF+IR,ICOLOF+JL)
     1                       +G*SMAT(ISTOFF+IR,JSTOFF+JL,KNDEX)
C
C 5. TERMS CONTAINING Y3*Y3
C
      KNDEX=KNDEX+1
      G=-G
      IF (.NOT. SYMM) G = VALASY(IOFFAS+2)
      DO 180 JL=1,NDIMCO
      DO 180 IR=1,NDIMRO
180   HMAT(IROWOF+IR,ICOLOF+JL)=HMAT(IROWOF+IR,ICOLOF+JL)
     1                       +G*SMAT(ISTOFF+IR,JSTOFF+JL,KNDEX)
C
C 6. TERMS CONTAINING Y1*Y3
C
      KNDEX=KNDEX+1
      G = VALSYM(IOFFSY+4)
      DO 200 JL=1,NDIMCO
      DO 200 IR=1,NDIMRO
200   HMAT(IROWOF+IR,ICOLOF+JL)=HMAT(IROWOF+IR,ICOLOF+JL)
     1                 +G*SMAT(ISTOFF+IR,JSTOFF+JL,KNDEX)
C
C  7. TERMS CONTAINING Y1*Y1*Y1
C
      KNDEX=KNDEX+1
      G = VALSYM(IOFFSY+5)
      DO 220 JL=1,NDIMCO
      DO 220 IR=1,NDIMRO
220   HMAT(IROWOF+IR,ICOLOF+JL)=HMAT(IROWOF+IR,ICOLOF+JL)
     1                       +G*SMAT(ISTOFF+IR,JSTOFF+JL,KNDEX)
C
C 8. TERMS CONTAINING Y3*Y3*Y3
C
      KNDEX=KNDEX+1
      G=-G
      IF (.NOT. SYMM) G = VALASY(IOFFAS+3)
      DO 240 JL=1,NDIMCO
      DO 240 IR=1,NDIMRO
240   HMAT(IROWOF+IR,ICOLOF+JL)=HMAT(IROWOF+IR,ICOLOF+JL)
     1                       +G*SMAT(ISTOFF+IR,JSTOFF+JL,KNDEX)
C
C  9. TERMS CONTAINING Y1*Y1*Y3
C
      KNDEX=KNDEX+1
      G = VALSYM(IOFFSY+6)
      DO 260 JL=1,NDIMCO
      DO 260 IR=1,NDIMRO
260   HMAT(IROWOF+IR,ICOLOF+JL)=HMAT(IROWOF+IR,ICOLOF+JL)
     1                       +G*SMAT(ISTOFF+IR,JSTOFF+JL,KNDEX)
C
C 10. TERMS CONTAINING Y1*Y3*Y3
C
      KNDEX=KNDEX+1
      G=-G
      IF (.NOT. SYMM) G = VALASY(IOFFAS+4)
      DO 280 JL=1,NDIMCO
      DO 280 IR=1,NDIMRO
280   HMAT(IROWOF+IR,ICOLOF+JL)=HMAT(IROWOF+IR,ICOLOF+JL)
     1                   +G*SMAT(ISTOFF+IR,JSTOFF+JL,KNDEX)
C
C  11. TERMS CONTAINING Y1*Y1*Y1*Y1
C
      KNDEX=KNDEX+1
      G = VALSYM(IOFFSY+7)
      DO 300 JL=1,NDIMCO
      DO 300 IR=1,NDIMRO
300   HMAT(IROWOF+IR,ICOLOF+JL)=HMAT(IROWOF+IR,ICOLOF+JL)
     1                       +G*SMAT(ISTOFF+IR,JSTOFF+JL,KNDEX)
C
C 12. TERMS CONTAINING Y3*Y3*Y3*Y3
C
      KNDEX=KNDEX+1
      G=-G
      IF (.NOT. SYMM) G = VALASY(IOFFAS+5)
      DO 320 JL=1,NDIMCO
      DO 320 IR=1,NDIMRO
320   HMAT(IROWOF+IR,ICOLOF+JL)=HMAT(IROWOF+IR,ICOLOF+JL)
     1                       +G*SMAT(ISTOFF+IR,JSTOFF+JL,KNDEX)
C
C  13. TERMS CONTAINING Y1*Y1*Y1*Y3
C
      KNDEX=KNDEX+1
      G = VALSYM(IOFFSY+8)
      DO 340 JL=1,NDIMCO
      DO 340 IR=1,NDIMRO
340   HMAT(IROWOF+IR,ICOLOF+JL)=HMAT(IROWOF+IR,ICOLOF+JL)
     1                       +G*SMAT(ISTOFF+IR,JSTOFF+JL,KNDEX)
C
C 14. TERMS CONTAINING Y1*Y3*Y3*Y3
C
      KNDEX=KNDEX+1
      G=-G
      IF (.NOT. SYMM) G = VALASY(IOFFAS+6)
      DO 360 JL=1,NDIMCO
      DO 360 IR=1,NDIMRO
360   HMAT(IROWOF+IR,ICOLOF+JL)=HMAT(IROWOF+IR,ICOLOF+JL)
     1                       +G*SMAT(ISTOFF+IR,JSTOFF+JL,KNDEX)
C
C 15. TERMS CONTAINING Y1*Y1*Y3*Y3
C
      KNDEX=KNDEX+1
      G = VALSYM(IOFFSY+9)
      DO 380 JL=1,NDIMCO
      DO 380 IR=1,NDIMRO
380   HMAT(IROWOF+IR,ICOLOF+JL)=HMAT(IROWOF+IR,ICOLOF+JL)
     1                       +G*SMAT(ISTOFF+IR,JSTOFF+JL,KNDEX)
900   CONTINUE
920   CONTINUE
940   CONTINUE
C
C*************************************************************
C
C     WRITE OUT VIBRATIONAL DIPOLE MATRIX ELEMENTS
C
C*************************************************************
C
      IF (IDPMA .NE. 0) THEN
      SLABR='  '
      SLABC='  '
      CALL SYMLAB(NABSR,SYMM,SLABR)
      CALL SYMLAB(NABSC,SYMM,SLABC)
      KVAL=KKP1-1
      IF (SYMM) THEN
           WRITE (NFIL6,5580) SLABR,SLABC,
     1                        PSEUR,PSEUC,KVAL
      ELSE
           WRITE (NFIL6,5582) SLABR,SLABC,
     1                        PSEUR,PSEUC,KVAL
      ENDIF
      ISNT1=IDIMRO
      ISNT2=IDIMCO
      ISNT=ISNT1+ISNT2
      NCOLL=1
      NCOLU=ISNT2
      IF (NCOLU.GT.10) NCOLU=10
      NNDCO=IDIMCO/V2MP1C-1
      INDV21=0
      INSTR1=0
2700  LNDEX=0
      DO 2622 I=NCOLL,NCOLU
      LNDEX=LNDEX+1
      V2VAL(LNDEX)=INDV21
      NSVAL(LNDEX)=INSTR1
      IF (INSTR1 .EQ. NNDCO) THEN
            INDV21=INDV21+1
            INSTR1=0
      ELSE
            INSTR1=INSTR1+1
      ENDIF
2622  CONTINUE
      WRITE (NFIL6,5590) (V2VAL(I), I=1,1-NCOLL+NCOLU)
      WRITE (NFIL6,5592) (NSVAL(I), I=1,1-NCOLL+NCOLU)
      WRITE (NFIL6,5591)
      NNDRO=IDIMRO/V2MP1R-1
      INDV22=0
      INSTR2=0
      DO 2710 I=1,ISNT1
      WRITE (NFIL6,5540) INDV22,INSTR2,(HMAT(I,J), J=NCOLL,NCOLU)
      IF (INSTR2 .EQ. NNDRO) THEN
            INDV22=INDV22+1
            INSTR2=0
      ELSE
            INSTR2=INSTR2+1
      ENDIF
2710  CONTINUE
      IF (NCOLU.GE.ISNT2) GOTO 941
      NCOLL=NCOLL+10
      NCOLU=NCOLU+10
      IF (NCOLU.GT.ISNT2) NCOLU=ISNT2
      GOTO 2700
      ENDIF
941   CONTINUE
5540  FORMAT(' ',3X,I3,1X,I3,'   :',10F10.4)
5580  FORMAT(//'0',5X,12('*'),
     1       ' ',A,'-',A,' (KDEL = 0) MATRIX ELEMENTS ',
     1            'OF ',A1,A1,
     1       ' FOR K = ',I2,' (DEBYE) ',12('*')//)
5582  FORMAT(//'0',5X,12('*'),
     1       ' ',A,'-',A,' (KDEL = 0) MATRIX ELEMEN',
     1            'TS OF ',A1,A1,
     1       ' FOR K = ',I2,' (DEBYE) ',12('*')//)
5590  FORMAT('0',10X,'V2  ',10I10)
5592  FORMAT(' ',10X,'NB  ',10I10)
5591  FORMAT(' ',4X,'V2',2X,'NA'/' ',6X,108('-'))
      RETURN
      END
C
C
      SUBROUTINE MUEDK1(VALSYM,INTSYM,
     1                  VALASY,INTASY,
     1                  SMAT,NOBAL,NOBAR,NOPERS,
     1                  ISTOFF,JSTOFF,
     1                  HMAT,IDIMRO,IDIMCO,
     1                  NDIMRO,NDIMCO,
     1                  V2MP1R,V2MP1C,
     1                  JMAXP1,KK1P1,KKDEL,
     1                  NDIPSY,NDIPAS,
     1                  SYMM,
     1                  AABB,
     2                  NABSR,NABSC,
     1                  PSEUR,PSEUC)
C
      IMPLICIT REAL*8 (A-H,O-Z)
C
      COMMON /AMPDI/ IDPMA,IDPTR
C
      INTEGER PRTINT 
C
      LOGICAL SYMM,AABB
      INTEGER NABSR,NABSC
      CHARACTER*2 SLABR,SLABC
      CHARACTER*1 PSEUR,PSEUC 
      REAL*8 VALSYM(INTSYM)
      REAL*8 VALASY(INTASY)
      REAL*8 SMAT(NOBAL,NOBAR,NOPERS)
      REAL*8 HMAT(IDIMRO,IDIMCO)
      INTEGER V2MP1R,V2MP1C
C
      INTEGER V2VAL(10)
      INTEGER NSVAL(10)
C
      include 'rensys.h'
C
      CONCOR=PLANCK*AVOGNO*1.0E+16/(1.6E+01*PI*PI*VELLGT)
      CONYZ=CONCOR
      CONXR=CONCOR
      CONCOR=-CONCOR
      SQ2=SQRT(2.0D+00)
C
      KBDSYM=0
      KBDASY=0
C
      DO 93 JL=1,IDIMCO
      DO 93 IR=1,IDIMRO
93    HMAT(IR,JL)=0.0D+00
C
      DO 780 K1P1=1,JMAXP1
      DO 770 KDEL=-1,1,2
      K2P1=K1P1+KDEL
      IF (K2P1 .LT. 1 .OR. K2P1 .GT. JMAXP1) GOTO 770
C
      DO 760 INDEX1=1,V2MP1R
      DO 750 INDEX2=1,V2MP1C
C
C
      KBDSYM=KBDSYM+1
      IOFFSY=(KBDSYM-1)*NDIPSY
      IF (.NOT.SYMM) THEN
          KBDASY=KBDASY+1
          IOFFAS=(KBDASY-1)*NDIPAS
      ENDIF
C
      IF (KKDEL.NE.KDEL) GOTO 750
      IF (KK1P1.NE.K1P1) GOTO 750
C
      KNDEX=0
C
      IROWOF=(INDEX1-1)*NDIMRO
      ICOLOF=(INDEX2-1)*NDIMCO
C
C
C  1. LEADING TERM (NOT DEPENDING ON STRETCHING COORDINATES)
C
      IF (AABB) THEN
      G=VALSYM(IOFFSY+1)
      DO 100 IR=1,NDIMRO
100   HMAT(IROWOF+IR,ICOLOF+IR)=HMAT(IROWOF+IR,ICOLOF+IR)
     1                       +G
      ELSE
      G=VALSYM(IOFFSY+1)
      KNDEX=KNDEX+1
      DO 101 IR=1,NDIMRO
      DO 101 JL=1,NDIMCO
101   HMAT(IROWOF+IR,ICOLOF+JL)=HMAT(IROWOF+IR,ICOLOF+JL)
     1                       +G*SMAT(ISTOFF+IR,JSTOFF+JL,KNDEX)
      ENDIF 
C
C  2. TERMS CONTAINING Y1
C
      KNDEX=KNDEX+1
       G = VALSYM(IOFFSY+2)
      DO 120 JL=1,NDIMCO
      DO 120 IR=1,NDIMRO
120   HMAT(IROWOF+IR,ICOLOF+JL)=HMAT(IROWOF+IR,ICOLOF+JL)
     1                       +G*SMAT(ISTOFF+IR,JSTOFF+JL,KNDEX)
C
C 3. TERMS CONTAINING Y3
C
      KNDEX=KNDEX+1
      IF (.NOT. SYMM) G = VALASY(IOFFAS+1)
      DO 140 JL=1,NDIMCO
      DO 140 IR=1,NDIMRO
140   HMAT(IROWOF+IR,ICOLOF+JL)=HMAT(IROWOF+IR,ICOLOF+JL)
     1                       +G*SMAT(ISTOFF+IR,JSTOFF+JL,KNDEX)
C
C  4. TERMS CONTAINING Y1*Y1
C
      KNDEX=KNDEX+1
       G = VALSYM(IOFFSY+3)
      DO 160 JL=1,NDIMCO
      DO 160 IR=1,NDIMRO
160   HMAT(IROWOF+IR,ICOLOF+JL)=HMAT(IROWOF+IR,ICOLOF+JL)
     1                       +G*SMAT(ISTOFF+IR,JSTOFF+JL,KNDEX)
C
C 5. TERMS CONTAINING Y3*Y3
C
      KNDEX=KNDEX+1
      IF (.NOT. SYMM) G = VALASY(IOFFAS+2)
      DO 180 JL=1,NDIMCO
      DO 180 IR=1,NDIMRO
180   HMAT(IROWOF+IR,ICOLOF+JL)=HMAT(IROWOF+IR,ICOLOF+JL)
     1                       +G*SMAT(ISTOFF+IR,JSTOFF+JL,KNDEX)
C
C 6. TERMS CONTAINING Y1*Y3
C
      KNDEX=KNDEX+1
       G = VALSYM(IOFFSY+4)
      DO 200 JL=1,NDIMCO
      DO 200 IR=1,NDIMRO
200   HMAT(IROWOF+IR,ICOLOF+JL)=HMAT(IROWOF+IR,ICOLOF+JL)
     1                       +G*SMAT(ISTOFF+IR,JSTOFF+JL,KNDEX)
C
C  7. TERMS CONTAINING Y1*Y1*Y1
C
      KNDEX=KNDEX+1
       G = VALSYM(IOFFSY+5)
      DO 220 JL=1,NDIMCO
      DO 220 IR=1,NDIMRO
220   HMAT(IROWOF+IR,ICOLOF+JL)=HMAT(IROWOF+IR,ICOLOF+JL)
     1                       +G*SMAT(ISTOFF+IR,JSTOFF+JL,KNDEX)
C
C 8. TERMS CONTAINING Y3*Y3*Y3
C
      KNDEX=KNDEX+1
      IF (.NOT. SYMM) G = VALASY(IOFFAS+3)
      DO 240 JL=1,NDIMCO
      DO 240 IR=1,NDIMRO
240   HMAT(IROWOF+IR,ICOLOF+JL)=HMAT(IROWOF+IR,ICOLOF+JL)
     1                       +G*SMAT(ISTOFF+IR,JSTOFF+JL,KNDEX)
C
C  9. TERMS CONTAINING Y1*Y1*Y3
C
      KNDEX=KNDEX+1
       G = VALSYM(IOFFSY+6)
      DO 260 JL=1,NDIMCO
      DO 260 IR=1,NDIMRO
260   HMAT(IROWOF+IR,ICOLOF+JL)=HMAT(IROWOF+IR,ICOLOF+JL)
     1                       +G*SMAT(ISTOFF+IR,JSTOFF+JL,KNDEX)
C
C 10. TERMS CONTAINING Y1*Y3*Y3
C
      KNDEX=KNDEX+1
      IF (.NOT. SYMM) G = VALASY(IOFFAS+4)
      DO 280 JL=1,NDIMCO
      DO 280 IR=1,NDIMRO
280   HMAT(IROWOF+IR,ICOLOF+JL)=HMAT(IROWOF+IR,ICOLOF+JL)
     1                       +G*SMAT(ISTOFF+IR,JSTOFF+JL,KNDEX)
C
C  11. TERMS CONTAINING Y1*Y1*Y1*Y1
C
      KNDEX=KNDEX+1
       G = VALSYM(IOFFSY+7)
      DO 300 JL=1,NDIMCO
      DO 300 IR=1,NDIMRO
300   HMAT(IROWOF+IR,ICOLOF+JL)=HMAT(IROWOF+IR,ICOLOF+JL)
     1                       +G*SMAT(ISTOFF+IR,JSTOFF+JL,KNDEX)
C
C 12. TERMS CONTAINING Y3*Y3*Y3*Y3
C
      KNDEX=KNDEX+1
      IF (.NOT. SYMM) G = VALASY(IOFFAS+5)
      DO 320 JL=1,NDIMCO
      DO 320 IR=1,NDIMRO
320   HMAT(IROWOF+IR,ICOLOF+JL)=HMAT(IROWOF+IR,ICOLOF+JL)
     1                       +G*SMAT(ISTOFF+IR,JSTOFF+JL,KNDEX)
C
C  13. TERMS CONTAINING Y1*Y1*Y1*Y3
C
      KNDEX=KNDEX+1
       G = VALSYM(IOFFSY+8)
      DO 340 JL=1,NDIMCO
      DO 340 IR=1,NDIMRO
340   HMAT(IROWOF+IR,ICOLOF+JL)=HMAT(IROWOF+IR,ICOLOF+JL)
     1                       +G*SMAT(ISTOFF+IR,JSTOFF+JL,KNDEX)
C
C 14. TERMS CONTAINING Y1*Y3*Y3*Y3
C
      KNDEX=KNDEX+1
      IF (.NOT. SYMM) G = VALASY(IOFFAS+6)
      DO 360 JL=1,NDIMCO
      DO 360 IR=1,NDIMRO
360   HMAT(IROWOF+IR,ICOLOF+JL)=HMAT(IROWOF+IR,ICOLOF+JL)
     1                       +G*SMAT(ISTOFF+IR,JSTOFF+JL,KNDEX)
C
C 15. TERMS CONTAINING Y1*Y1*Y3*Y3
C
      KNDEX=KNDEX+1
       G = VALSYM(IOFFSY+9)
      DO 380 JL=1,NDIMCO
      DO 380 IR=1,NDIMRO
380   HMAT(IROWOF+IR,ICOLOF+JL)=HMAT(IROWOF+IR,ICOLOF+JL)
     1                       +G*SMAT(ISTOFF+IR,JSTOFF+JL,KNDEX)
750   CONTINUE
760   CONTINUE
770   CONTINUE
780   CONTINUE
C
C*************************************************************
C
C     WRITE OUT VIBRATIONAL DIPOLE MATRIX ELEMENTS
C
C*************************************************************
C
C     IF (KKDEL .EQ. -1) GOTO 771
C
      IF (IDPMA .NE. 0) THEN
      SLABR='  '
      SLABC='  '
      CALL SYMLAB(NABSR,SYMM,SLABR)
      CALL SYMLAB(NABSC,SYMM,SLABC)
      IF (ISTOFF .EQ. 0) THEN
      KVAL=KK1P1-1
      IF (SYMM) THEN
           WRITE (NFIL6,5500) SLABR,SLABC,
     1                        KKDEL,PSEUR,PSEUC,KVAL
      ELSE
           WRITE (NFIL6,5502) SLABR,SLABC,
     1                        KKDEL,PSEUR,PSEUC,KVAL
      ENDIF
      ISNT=IDIMRO
      NCOLL=1
      NCOLU=ISNT
      IF (NCOLU.GT.10) NCOLU=10
      NNDEX=IDIMRO/V2MP1R-1
      INDV21=0
      INSTR1=0
2620  NUP=NCOLU
      IF (NUP.GT.ISNT) NUP=ISNT
      LNDEX=0
      DO 2622 I=NCOLL,NUP
      LNDEX=LNDEX+1
      V2VAL(LNDEX)=INDV21
      NSVAL(LNDEX)=INSTR1
      IF (INSTR1 .EQ. NNDEX) THEN
            INDV21=INDV21+1
            INSTR1=0
      ELSE
            INSTR1=INSTR1+1
      ENDIF
2622  CONTINUE
      WRITE (NFIL6,5520) (V2VAL(I), I=1,1-NCOLL+NUP)
      WRITE (NFIL6,5522) (NSVAL(I), I=1,1-NCOLL+NUP)
      WRITE (NFIL6,5521)
      INDV22=0
      INSTR2=0
      DO 2630 I=1,ISNT
      NUP=NCOLU
      WRITE (NFIL6,5540) INDV22,INSTR2,(HMAT(I,J), J=NCOLL,NUP)
      IF (INSTR2 .EQ. NNDEX) THEN
            INDV22=INDV22+1
            INSTR2=0
      ELSE
            INSTR2=INSTR2+1
      ENDIF
2630  CONTINUE
      IF (NCOLU.GE.ISNT) GOTO 2640
      NCOLL=NCOLL+10
      NCOLU=NCOLU+10
      IF (NCOLU.GT.ISNT) NCOLU=ISNT
      GOTO 2620
2640  CONTINUE
      ELSE
      KVAL=KK1P1-1
      SLABR='  '
      SLABC='  '
      CALL SYMLAB(INDSYR,SYMM,SLABR)
      CALL SYMLAB(INDSYC,SYMM,SLABC)
      WRITE (NFIL6,5560) SLABR,SLABC,
     1                   KKDEL,PSEUR,PSEUC,KVAL
      ISNT=IDIMRO
      NCOLL=1
      NCOLU=ISNT
      IF (NCOLU.GT.10) NCOLU=10
      NNDEX=IDIMRO/V2MP1R-1
      INDV21=0
      INSTR1=0
2660  NUP=NCOLU
      IF (NUP.GT.ISNT) NUP=ISNT
      LNDEX=0
      DO 2662 I=NCOLL,NUP
      LNDEX=LNDEX+1
      V2VAL(LNDEX)=INDV21
      NSVAL(LNDEX)=INSTR1
      IF (INSTR1 .EQ. NNDEX) THEN
            INDV21=INDV21+1
            INSTR1=0
      ELSE
            INSTR1=INSTR1+1
      ENDIF
2662  CONTINUE
      WRITE (NFIL6,5570) (V2VAL(I), I=1,1-NCOLL+NUP)
      WRITE (NFIL6,5572) (NSVAL(I), I=1,1-NCOLL+NUP)
      WRITE (NFIL6,5571)
      INDV22=0
      INSTR2=0
      DO 2670 I=1,ISNT
      NUP=NCOLU
      WRITE (NFIL6,5540) INDV22,INSTR2,(HMAT(I,J), J=NCOLL,NUP)
      IF (INSTR2 .EQ. NNDEX) THEN
            INDV22=INDV22+1
            INSTR2=0
      ELSE
            INSTR2=INSTR2+1
      ENDIF
2670  CONTINUE
      IF (NCOLU.GE.ISNT) GOTO 2680
      NCOLL=NCOLL+10
      NCOLU=NCOLU+10
      IF (NCOLU.GT.ISNT) NCOLU=ISNT
      GOTO 2660
2680  CONTINUE
      ENDIF
      ENDIF
771   CONTINUE 
      RETURN
5500  FORMAT(// '0',5X,12('*'),' ',A,'-',A,' (KDEL = ',I2,
     1 ' MATRIX ELEMENTS ',
     1 'OF ',A1,A1,' FOR K = ',I2,' (DEBYE) ',12('*')//)
5502  FORMAT(// '0',5X,12('*'),' ',A,'-',A,' (KDEL = ',I2,
     1 ' MATRIX ELEMENTS ',
     1 'OF ',A1,A1,' FOR K = ',I2,' (DEBYE) ',12('*')//)
5520  FORMAT('0',10X,'V2  ',10I10)
5522  FORMAT(' ',10X,'NA  ',10I10)
5521  FORMAT(' ',4X,'V2',2X,'NA'/' ',6X,108('-'))
5540  FORMAT(' ',3X,I3,1X,I3,'   :',10F10.4)
5560  FORMAT(//'0',5X,12('*'),' ',A,'-',A, ' (KDEL = ',I2,
     1 ' MATRIX ELEMENTS ',
     1 'OF ',A1,A1,' FOR K = ',I2,' (DEBYE) ',12('*')//)
5570  FORMAT('0',10X,'V2  ',10I10)
5572  FORMAT(' ',10X,'NB  ',10I10)
5571  FORMAT(' ',4X,'V2',2X,'NB'/' ',6X,108('-'))
      END
C****************************************
      SUBROUTINE SYMLAB(NABS,SYMM,SLAB)
C****************************************
      INTEGER NABS
      LOGICAL SYMM
      CHARACTER*2 SLAB
C
      SLAB='  '
C
      IF (SYMM) THEN
         IF (NABS.EQ.1) THEN
            SLAB='A1'
         ELSE
            SLAB='B2'
         ENDIF
      ELSE
         SLAB='A'''
      ENDIF
C
      RETURN
      END
